Implement pending spec
clearhaus/pedicel pull request #16
Opened 2018-05-31 11:56 UTC by ct-clearhaus

Alternatively we should adjust PedicelPay to allow for this, but I think it is quite a tight corner case, so we could accept this 💩 spec or just not spec it. WDYT?

2018-05-31 12:20 UTC, mt-clearhaus requested changes
I see no harm in having this spec. We can change PedicelPay later if the need arises and then simplify this spec.

2018-05-31 12:20 UTC, mt-clearhaus commented on spec/lib/pedicel/base_spec.rb
> +      it 'handles that once certificate can be both intermediate and leaf', me:true do
`me:true`

2018-05-31 12:20 UTC, mt-clearhaus commented on spec/lib/pedicel/base_spec.rb
> +      it 'handles that once certificate can be both intermediate and leaf', me:true do
s/once certificate/one certificate/

2018-05-31 12:45 UTC, ct-clearhaus commented on spec/lib/pedicel/base_spec.rb
> +      it 'handles that once certificate can be both intermediate and leaf', me:true do
🙇

2018-05-31 12:47 UTC, mt-clearhaus submitted a review, later dismissed

2018-05-31 12:49 UTC, ct-clearhaus commented
It's quite mystifying why the specs now fail on Ruby 2.3.7; it seems `libssl-dev` is missing.

2018-05-31 13:22 UTC, mt-clearhaus commented
However, it certainly is missing from 2.3.7 :confused: 

```
$ docker run --rm -it ruby:2.3.3 bash -c 'find / -type f -name evp.h'
/usr/include/openssl/evp.h
$ docker run --rm -it ruby:2.3.7 bash -c 'find / -type f -name evp.h'
# no output

$ docker run --rm -it ruby:2.3.3 bash -c 'dpkg -l | grep -o " libssl-dev"'
 libssl-dev
$ docker run --rm -it ruby:2.3.7 bash -c 'dpkg -l | grep -o " libssl-dev"'
# no output
```

2018-05-31 13:34 UTC, mt-clearhaus commented
It we say that one cannot expect OpenSSL development libraries to be installed in a generic Ruby Docker image, a solution could be to always explicitly install them... Something like the following CircleCI config diff might work.

```
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,20 +1,26 @@
 version: 2
 
+common_steps: &common_steps
+  - checkout
+  - run:
+      name: Prepare environment
+      command: |
+        apt-get update
+        apt-get install -y --no-install-recommends libssl-dev
+        bundle install
+  - run:
+      name: Test
+      command: bundle exec rake test
+
 jobs:
   ruby233:
     docker:
       - image: ruby:2.3.3
-    steps:
-      - checkout
-      - run: bundle install
-      - run: bundle exec rake test
+    steps: *common_steps
   ruby237:
     docker:
       - image: ruby:2.3.7
-    steps:
-      - checkout
-      - run: bundle install
-      - run: bundle exec rake test
+    steps: *common_steps
 
 workflows:
   version: 2
```

2018-05-31 13:37 UTC, mt-clearhaus commented
It works :slightly_smiling_face: https://circleci.com/gh/clearhaus/pedicel/105

2018-06-01 06:06 UTC, ct-clearhaus reviewed
Great! 👍

2018-06-01 11:12 UTC, mt-clearhaus approved these changes

2018-06-01 11:13 UTC, merged